version: 2.1

jobs:
  build:
    docker:
      - image: tuplestream/golang:latest
    steps:
      - checkout
      - run:
          name: build and test source
          command: |
            export CGO_ENABLED=0
            go vet
            go test
  bump_version:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - checkout
      - run: bump

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - bump_version:
          requires:
            - build
          filters:
            branches:
              only: master