version: 2.1

jobs:
  build:
    docker:
      - image: tuplestream/golang:latest
    steps:
      - checkout
      - run:
          name: build and test source
          command: |
            export CGO_ENABLED=0
            go vet
            apk add curl jq
            export TUPLESTREAM_KEY=$(curl --request POST --url 'https://dev-ak43b46u.eu.auth0.com/oauth/token' -H 'content-type: application/x-www-form-urlencoded' --data grant_type=password --data 'password=$DUMMY_PASSWORD' --data username=$DUMMY_EMAIL --data audience=$DUMMY_AUDIENCE --data scope=logstream --data client_id=$DUMMY_CLIENT_ID --data client_secret=$DUMMY_CLIENT_SECRET | jq -r '.access_token')
            echo $TUPLESTREAM_KEY
  bump_version:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - checkout
      - run: bump

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - bump_version:
          requires:
            - build
          filters:
            branches:
              only: master
